[package]
name = "client-cpp"
version = "0.1.0"
authors = ["The TiKV Project Authors"]
edition = "2018"

[lib]
name = "tikv_client_rust"
crate-type = ["staticlib"]

[dependencies]
anyhow = "1"
cxx = "=1.0.75"
futures = "0.3"
once_cell = "1.9.0"
tokio = { version = "1", features = [ "sync", "rt-multi-thread", "macros" ] }
env_logger = "0.9"
tikv-client = { git = "https://github.com/bxq2011hust/tikv-client-rust.git", rev = "b941bcce760fccf90af1c2f72a05c665499165de" }
